
- name: Install Nginx
  apt:
    name: nginx
    state: present 
    update_cache: yes 

- name: Remove default Nginx site if it exists
  file:
    path: /etc/nginx/sites-enabled/default 
    state: absent 
  notify: Reload Nginx Service

- name: Copy reverse proxy configuration file
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse_proxy
  notify:
    - Validate Nginx Configuration
    - Fail if Nginx Configuration is Invalid
    - Reload Nginx Service

- name: Enable reverse proxy configuration
  file:
    src: /etc/nginx/sites-available/reverse_proxy
    dest: /etc/nginx/sites-enabled/reverse_proxy 
    state: link
  notify: Reload Nginx Service

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started 
    enabled: yes 
