# tasks/main.yml
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Copy index.html file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restart web server

- name: Ensure Apache is running
  service:
    name: httpd
    state: started
    enabled: yes